"""empty message

Revision ID: 2bdb50bf6b00
Revises: 48b2d5c01c2a
Create Date: 2020-09-28 17:00:50.141004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bdb50bf6b00'
down_revision = '48b2d5c01c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('account_name', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('account_no', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('account_type', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('address', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('bank_branch', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('canceled_check_link', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('city', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('client_url', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('country', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('gst_cert_url', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('gst_number', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('ifsc_code', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('pan_number', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('pincode', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'state')
    op.drop_column('clients', 'pincode')
    op.drop_column('clients', 'pan_number')
    op.drop_column('clients', 'ifsc_code')
    op.drop_column('clients', 'gst_number')
    op.drop_column('clients', 'gst_cert_url')
    op.drop_column('clients', 'country')
    op.drop_column('clients', 'client_url')
    op.drop_column('clients', 'city')
    op.drop_column('clients', 'canceled_check_link')
    op.drop_column('clients', 'bank_name')
    op.drop_column('clients', 'bank_branch')
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'account_type')
    op.drop_column('clients', 'account_no')
    op.drop_column('clients', 'account_name')
    # ### end Alembic commands ###
