"""empty message

Revision ID: 3cecde758164
Revises: fdecad49e219
Create Date: 2020-11-11 12:25:42.119383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3cecde758164'
down_revision = 'fdecad49e219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('thirdwatch', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'thirdwatch')
    # ### end Alembic commands ###
