"""empty message

Revision ID: 48b2d5c01c2a
Revises: f6dd4419fd30
Create Date: 2020-09-10 18:30:51.383662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b2d5c01c2a'
down_revision = 'f6dd4419fd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_as', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['login_as'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'login_as')
    # ### end Alembic commands ###
