"""empty message

Revision ID: 5d1012bb72f2
Revises: 
Create Date: 2019-11-02 08:40:07.680290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1012bb72f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(length=128), nullable=False),
    sa.Column('client_prefix', sa.String(length=32), nullable=False),
    sa.Column('primary_email', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_name'),
    sa.UniqueConstraint('client_prefix'),
    sa.UniqueConstraint('primary_email')
    )
    op.add_column('users', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_foreign_key(None, 'users', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'client_id')
    op.drop_table('clients')
    # ### end Alembic commands ###
