"""empty message

Revision ID: b8268841047d
Revises: a6c82a9c3e95
Create Date: 2020-08-12 16:37:35.055217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8268841047d'
down_revision = 'a6c82a9c3e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('calling_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_no', sa.String(length=13), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_no')
    op.drop_column('users', 'calling_active')
    # ### end Alembic commands ###
