"""empty message

Revision ID: ee33f51cd8cb
Revises: 3cecde758164
Create Date: 2020-11-11 12:30:26.419713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee33f51cd8cb'
down_revision = '3cecde758164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('thirdwatch', sa.Boolean(), nullable=True))
    op.drop_column('users', 'thirdwatch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('thirdwatch', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('clients', 'thirdwatch')
    # ### end Alembic commands ###
