"""empty message

Revision ID: f6dd4419fd30
Revises: b8268841047d
Create Date: 2020-09-08 16:55:56.816030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6dd4419fd30'
down_revision = 'b8268841047d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('clients', sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('clients', sa.Column('tabs', postgresql.ARRAY(sa.String(length=20)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'tabs')
    op.drop_column('clients', 'created_date')
    op.drop_column('clients', 'active')
    # ### end Alembic commands ###
