ecom_express_status_mapping = {"310": ("READY TO SHIP", "UD", ""),
                             "303": ("IN TRANSIT", "UD", "In Transit"),
                             "400": ("IN TRANSIT", "UD", "In Transit"),
                             "003": ("IN TRANSIT", "UD", "In Transit"),
                             "002": ("IN TRANSIT", "UD", "In Transit"),
                             "005": ("IN TRANSIT", "UD", "In Transit"),
                             "0011": ("IN TRANSIT", "UD", "Picked"),
                             "006": ("DISPATCHED", "UD", "Out for delivery"),
                             "888": ("DAMAGED", "UD", ""),
                             "302": ("DAMAGED", "UD", ""),
                             "555": ("DESTROYED", "UD", ""),
                             "88802": ("DESTROYED", "UD", ""),
                             "88803": ("DESTROYED", "UD", ""),
                             "88804": ("DESTROYED", "UD", ""),
                             "31701": ("DESTROYED", "UD", ""),
                             "311": ("SHORTAGE", "UD", ""),
                             "313": ("SHORTAGE", "UD", ""),
                             "314": ("DAMAGED", "UD", ""),
                             "999": ("DELIVERED", "DL", "Delivered"),
                             "204": ("DELIVERED", "DL", "Delivered"),
                             "777": ("RTO", "DL", "Returned"),
                             "333": ("LOST", "UD", ""),
                             "33306": ("LOST", "UD", ""),
                             "33307": ("LOST", "UD", ""),
                             "228": ("PENDING", "UD", "In Transit"),
                             "227": ("PENDING", "UD", "In Transit"),
                             "226": ("PENDING", "UD", "In Transit"),
                             "224": ("PENDING", "UD", "In Transit"),
                             "223": ("PENDING", "UD", "In Transit"),
                             "222": ("PENDING", "UD", "In Transit"),
                             "220": ("PENDING", "UD", "In Transit"),
                             "418": ("PENDING", "UD", "In Transit"),
                             "417": ("PENDING", "UD", "In Transit"),
                             "219": ("PENDING", "UD", "In Transit"),
                             "218": ("PENDING", "UD", "In Transit"),
                             "231": ("PENDING", "UD", "In Transit"),
                             "212": ("PENDING", "UD", "In Transit"),
                             "217": ("PENDING", "UD", "In Transit"),
                             "213": ("PENDING", "UD", "In Transit"),
                             "331": ("PENDING", "UD", "In Transit"),
                             "210": ("PENDING", "UD", "Cancelled"),
                             "209": ("PENDING", "UD", "In Transit"),
                             "419": ("PENDING", "UD", "In Transit"),
                             "401": ("PENDING", "UD", "In Transit"),
                             "421": ("PENDING", "UD", "In Transit"),
                             "23101": ("PENDING", "UD", "In Transit"),
                             "23102": ("PENDING", "UD", "In Transit"),
                             "23103": ("PENDING", "UD", "In Transit"),
                             "22701": ("PENDING", "UD", "In Transit"),
                             "20002": ("PENDING", "UD", "In Transit"),
                             "21002": ("PENDING", "UD", "Cancelled"),
                             "22301": ("PENDING", "UD", "In Transit"),
                             "22303": ("PENDING", "UD", "In Transit"),
                             "23401": ("PENDING", "UD", "In Transit"),
                             "23402": ("PENDING", "UD", "In Transit"),
                             "22702": ("PENDING", "UD", "In Transit"),
                             "22801": ("PENDING", "UD", "In Transit"),
                             "22901": ("PENDING", "UD", "In Transit"),
                             "2447": ("PENDING", "UD", "In Transit"),
                             "2445": ("PENDING", "UD", "In Transit"),
                             }

ecom_express_ndr_reasons = {
                              "228": 8,
                              "227": 6,
                              "226": 4,
                              "224": 2,
                              "223": 2,
                              "222": 2,
                              "220": 2,
                              "418": 2,
                              "417": 2,
                              "219": 1,
                              "218": 1,
                              "231": 1,
                              "212": 1,
                              "217": 7,
                              "213": 4,
                              "331": 4,
                              "210": 3,
                              "209": 9,
                              "419": 13,
                              "401": 6,
                              "421": 1,
                              "23101": 1,
                              "23102": 1,
                              "23103": 1,
                              "232": 2,
                              "234": 2,
                              "22701": 6,
                              "20002": 11,
                              "21002": 3,
                              "22301": 2,
                              "22303": 2,
                              "23401": 2,
                              "23402": 2,
                              "2447": 2,
                              "22702": 6,
                              "22801": 8,
                              "22901": 5,
                              "2445": 9,
                            }