ecom_express_status_mapping = {"303": ("IN TRANSIT", "UD", "In Transit", "Shipment In Transit"),
                             "400": ("IN TRANSIT", "UD", "Picked", "Shipment picked up"),
                             "003": ("IN TRANSIT", "UD", "In Transit", "Bag scanned at DC"),
                             "002": ("IN TRANSIT", "UD", "In Transit", "Shipment in-scan"),
                             "004": ("IN TRANSIT", "UD", "In Transit", "Shipment in-scan"),
                             "005": ("IN TRANSIT", "UD", "In Transit", "Shipment in-scan at DC"),
                             "0011": ("IN TRANSIT", "UD", "Picked", "Shipment picked up"),
                             "21601": ("IN TRANSIT", "UD", "In Transit", "Late arrival-Misconnection/After cut off"),
                             "006": ("DISPATCHED", "UD", "Out for delivery", "Shipment out for delivery"),
                             "888": ("DAMAGED", "UD", "", "Transit Damage"),
                             "302": ("DAMAGED", "UD", "", "Transit Damage"),
                             "555": ("DESTROYED", "UD", "", "Destroyed Red Bus Shipment"),
                             "88802": ("DESTROYED", "UD", "", "Shipment destroyed - contains liquid item"),
                             "88803": ("DESTROYED", "UD", "", "Shipment destroyed - contains fragile item"),
                             "88804": ("DESTROYED", "UD", "", "Shipment destroyed - empty packet"),
                             "31701": ("DESTROYED", "UD", "", "Shipment destroyed - food item"),
                             "311": ("SHORTAGE", "UD", "", "Shortage"),
                             "313": ("SHORTAGE", "UD", "", "Shortage"),
                             "314": ("DAMAGED", "UD", "", "DMG Lock - Damage"),
                             "999": ("DELIVERED", "DL", "Delivered", "Shipment delivered"),
                             "204": ("DELIVERED", "DL", "Delivered", "Shipment delivered"),
                             "777": ("IN TRANSIT", "RT", "Returned", "Returned"),
                             "333": ("LOST", "UD", "", "Shipment Lost"),
                             "33306": ("LOST", "UD", "", "Shipment Lost"),
                             "33307": ("LOST", "UD", "", "Shipment Lost"),
                             "228": ("PENDING", "UD", "In Transit", "Out of Delivery Area"),
                             "227": ("PENDING", "UD", "In Transit", "Residence/Office Closed"),
                             "226": ("PENDING", "UD", "In Transit", "Holiday/Weekly off - Delivery on Next Working Day"),
                             "224": ("PENDING", "UD", "In Transit", "Address Unlocatable"),
                             "223": ("PENDING", "UD", "In Transit", "Address Incomplete"),
                             "222": ("PENDING", "UD", "In Transit", "Address Incorrect"),
                             "220": ("PENDING", "UD", "In Transit", "No Such Consignee At Given Address"),
                             "418": ("PENDING", "UD", "In Transit", "Consignee Shifted, phone num wrong"),
                             "417": ("PENDING", "UD", "In Transit", "PHONE NUMBER NOT ANSWERING/ADDRESS NOT LOCATABLE"),
                             "219": ("PENDING", "UD", "In Transit", "Consignee Not Available"),
                             "218": ("PENDING", "UD", "In Transit", "Consignee Shifted from the Given Address"),
                             "231": ("PENDING", "UD", "In Transit", "Shipment attempted - Customer not available"),
                             "212": ("PENDING", "UD", "In Transit", "Consignee Out Of Station"),
                             "217": ("PENDING", "UD", "In Transit", "Delivery Area Not Accessible"),
                             "213": ("PENDING", "UD", "In Transit", "Scheduled for Next Day Delivery"),
                             "331": ("PENDING", "UD", "In Transit", "Consignee requested for future delivery "),
                             "210": ("PENDING", "UD", "Cancelled", "Shipment attempted - Customer refused to accept"),
                             "209": ("PENDING", "UD", "In Transit", "Consignee Refusing to Pay COD Amount"),
                             "419": ("PENDING", "UD", "In Transit", "Three attempts made, follow up closed"),
                             "401": ("PENDING", "UD", "In Transit", "CUSTOMER RES/OFF CLOSED"),
                             "421": ("PENDING", "UD", "In Transit", "Customer Number not reachable/Switched off"),
                             "23101": ("PENDING", "UD", "In Transit", "Customer out of station"),
                             "23102": ("PENDING", "UD", "In Transit", "Customer not in office"),
                             "23103": ("PENDING", "UD", "In Transit", "Customer not in residence"),
                             "22701": ("PENDING", "UD", "In Transit", "Case with Legal team"),
                             "20002": ("PENDING", "UD", "In Transit", "Forcefully opened by customer and returned"),
                             "21002": ("PENDING", "UD", "Cancelled", "Order already cancelled"),
                             "22301": ("PENDING", "UD", "In Transit", "Customer out of station"),
                             "22303": ("PENDING", "UD", "In Transit", "No Such Consignee At Given Address"),
                             "23401": ("PENDING", "UD", "In Transit", "Address pincode mismatch - Serviceable area"),
                             "23402": ("PENDING", "UD", "In Transit", "Address pincode mismatch - Non Serviceable area"),
                             "22702": ("PENDING", "UD", "In Transit", "Shipment attempted - Office closed"),
                             "22801": ("PENDING", "UD", "In Transit", "Customer Address out of delivery area"),
                             "22901": ("PENDING", "UD", "In Transit", "Customer requested for self collection"),
                             "2447": ("PENDING", "UD", "In Transit", "No such addressee in the given address"),
                             "2445": ("PENDING", "UD", "In Transit", "Cash amount Mismatch"),
                             "12247": ("PENDING", "UD", "In Transit", "Delivery Attempt to be made - Escalations"),
                             "12245": ("PENDING", "UD", "In Transit", "Delivery attempt to be made - FE Instructions"),
                             "20701": ("PENDING", "UD", "In Transit", "Misroute due to wrong pincode given by customer"),
                             "1220": (None, None, None, "Pickup Assigned"),
                             "1230": (None, None, None, "Out for Pickup"),
                             "1350": (None, None, None, "Pickup Failed, Shipment Not Ready"),
                             "1410": (None, None, None, "Pickup Rescheduled For Next Day"),
                             }

sfxsdd_status_mapping = {"ALLOTTED": ("READY TO SHIP", "UD", "Received", "Order Received"),
                            "ARRIVED": ("READY TO SHIP", "UD", "Received", "Order Received"),
                             "DISPATCHED": ("IN TRANSIT", "UD", "Picked", "Shipment picked up"),
                             "ARRIVED_CUSTOMER_DOORSTEP": ("DISPATCHED", "UD", "Out for delivery", "Shipment out for delivery"),
                             "DELIVERED": ("DELIVERED", "DL", "Delivered", "Shipment delivered"),
                             "CANCELLED": ("CANCELED", "UD", "Cancelled", "order cancelled"),
                             "CANCELLED_BY_CUSTOMER": ("CANCELED", "UD", "Cancelled", "order cancelled"),
                             "UNDELIVERED": ("IN TRANSIT", "RT", "Returned", "Order returned"),
                             "RETURNED_TO_SELLER": ("RTO", "DL", "RTO", "Order RTO")}

ecom_express_ndr_reasons = {
                              "228": 8,
                              "227": 6,
                              "226": 4,
                              "224": 2,
                              "223": 2,
                              "222": 2,
                              "220": 2,
                              "418": 2,
                              "417": 2,
                              "219": 1,
                              "218": 1,
                              "231": 1,
                              "212": 1,
                              "217": 7,
                              "213": 4,
                              "331": 4,
                              "210": 3,
                              "209": 9,
                              "419": 13,
                              "401": 6,
                              "421": 1,
                              "23101": 1,
                              "23102": 1,
                              "23103": 1,
                              "232": 2,
                              "234": 2,
                              "22701": 6,
                              "20002": 11,
                              "21002": 3,
                              "22301": 2,
                              "22303": 2,
                              "23401": 2,
                              "23402": 2,
                              "2447": 2,
                              "22702": 6,
                              "22801": 8,
                              "22901": 5,
                              "2445": 9,
                            }

zone_column_mapping = {
    'A': 'zone_a',
    'B': 'zone_b',
    'C': 'zone_c',
    'D': 'zone_d',
    'E': 'zone_e',
}

zone_step_charge_column_mapping = {
    'A': 'a_step',
    'B': 'b_step',
    'C': 'c_step',
    'D': 'd_step',
    'E': 'e_step'
}

zone_column_mapping_courier = {
    'A': 'zone_a',
    'B': 'zone_b',
    'C1': 'zone_c1',
    'C': 'zone_c1',
    'C2': 'zone_c2',
    'D1': 'zone_d1',
    'D': 'zone_d1',
    'D2': 'zone_d2',
    'E': 'zone_e',
}

nasher_zonal_mapping = {
    'A': [74, 9],
    'B': [107, 13],
    'C': [126, 15],
    'D': [144, 17],
    'E': [149, 17],
}

rto_heavy_1 = {
    'A': 11,
    'B': 12,
    'C1': 15,
    'C': 15,
    'C2': 15,
    'D1': 18,
    'D': 18,
    'D2': 18,
    'E': 21,
}

rto_heavy_2 = {
    'A': 10,
    'B': 12,
    'C1': 17,
    'C': 17,
    'C2': 17,
    'D1': 18,
    'D': 18,
    'D2': 18,
    'E': 22,
}

rto_bulk = {
    'A': 20,
    'B': 23,
    'C1': 24,
    'C': 24,
    'C2': 26,
    'D1': 28,
    'D': 28,
    'D2': 30,
    'E': 34,
}

bulk_second_step = {
    'A': 26,
    'B': 28,
    'C1': 30,
    'C': 30,
    'C2': 32,
    'D1': 36,
    'D': 36,
    'D2': 38,
    'E': 52,
}