FROM nginx:1.15.9-alpine

#RUN apk add --update sudo

#RUN apk add --update certbot

COPY ./fullchain-qa.pem /etc/fullchain.pem
COPY ./privkey-qa.pem /etc/privkey.pem

RUN rm /etc/nginx/conf.d/default.conf
COPY /qa.conf /etc/nginx/conf.d