"""empty message

Revision ID: 00edd95f0925
Revises: 4d9f8e8c17be
Create Date: 2019-11-24 17:09:14.449370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00edd95f0925'
down_revision = '4d9f8e8c17be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_couriers', sa.Column('unique_parameter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_couriers', 'unique_parameter')
    # ### end Alembic commands ###
