"""empty message

Revision ID: 01ce81f8225d
Revises: eb8b056796f6
Create Date: 2020-12-23 22:31:20.295292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ce81f8225d'
down_revision = 'eb8b056796f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_pickups', sa.Column('enable_sdd', sa.BOOLEAN(), nullable=True))
    op.add_column('products_quantity', sa.Column('sync_easyecom', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_quantity', 'sync_easyecom')
    op.drop_column('client_pickups', 'enable_sdd')
    # ### end Alembic commands ###
