"""empty message

Revision ID: 0420fd51d95f
Revises: d35e84603b5c
Create Date: 2020-01-12 22:15:14.022903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0420fd51d95f'
down_revision = 'd35e84603b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_to_clients', sa.Column('zone_c', sa.FLOAT(), nullable=True))
    op.add_column('cost_to_clients', sa.Column('zone_d', sa.FLOAT(), nullable=True))
    op.drop_column('cost_to_clients', 'zone_a_add')
    op.drop_column('cost_to_clients', 'zone_b_add')
    op.drop_column('cost_to_clients', 'zone_d1_add')
    op.drop_column('cost_to_clients', 'zone_d2_add')
    op.drop_column('cost_to_clients', 'zone_c1')
    op.drop_column('cost_to_clients', 'zone_c2')
    op.drop_column('cost_to_clients', 'zone_d2')
    op.drop_column('cost_to_clients', 'zone_e_add')
    op.drop_column('cost_to_clients', 'zone_c2_add')
    op.drop_column('cost_to_clients', 'zone_c1_add')
    op.drop_column('cost_to_clients', 'zone_d1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_to_clients', sa.Column('zone_d1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cost_to_clients', sa.Column('zone_c1_add', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cost_to_clients', sa.Column('zone_c2_add', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cost_to_clients', sa.Column('zone_e_add', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cost_to_clients', sa.Column('zone_d2', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cost_to_clients', sa.Column('zone_c2', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cost_to_clients', sa.Column('zone_c1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cost_to_clients', sa.Column('zone_d2_add', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cost_to_clients', sa.Column('zone_d1_add', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cost_to_clients', sa.Column('zone_b_add', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cost_to_clients', sa.Column('zone_a_add', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('cost_to_clients', 'zone_d')
    op.drop_column('cost_to_clients', 'zone_c')
    # ### end Alembic commands ###
