"""empty message

Revision ID: 04712497f469
Revises: ce0e0dfea34f
Create Date: 2020-02-10 20:41:11.839236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04712497f469'
down_revision = 'ce0e0dfea34f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cod_verification', sa.Column('click_browser', sa.String(), nullable=True))
    op.add_column('cod_verification', sa.Column('click_platform', sa.String(), nullable=True))
    op.add_column('cod_verification', sa.Column('click_string', sa.String(), nullable=True))
    op.add_column('cod_verification', sa.Column('click_version', sa.String(), nullable=True))
    op.add_column('delivery_check', sa.Column('click_browser', sa.String(), nullable=True))
    op.add_column('delivery_check', sa.Column('click_platform', sa.String(), nullable=True))
    op.add_column('delivery_check', sa.Column('click_string', sa.String(), nullable=True))
    op.add_column('delivery_check', sa.Column('click_version', sa.String(), nullable=True))
    op.add_column('ndr_verification', sa.Column('click_browser', sa.String(), nullable=True))
    op.add_column('ndr_verification', sa.Column('click_platform', sa.String(), nullable=True))
    op.add_column('ndr_verification', sa.Column('click_string', sa.String(), nullable=True))
    op.add_column('ndr_verification', sa.Column('click_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ndr_verification', 'click_version')
    op.drop_column('ndr_verification', 'click_string')
    op.drop_column('ndr_verification', 'click_platform')
    op.drop_column('ndr_verification', 'click_browser')
    op.drop_column('delivery_check', 'click_version')
    op.drop_column('delivery_check', 'click_string')
    op.drop_column('delivery_check', 'click_platform')
    op.drop_column('delivery_check', 'click_browser')
    op.drop_column('cod_verification', 'click_version')
    op.drop_column('cod_verification', 'click_string')
    op.drop_column('cod_verification', 'click_platform')
    op.drop_column('cod_verification', 'click_browser')
    # ### end Alembic commands ###
