"""empty message

Revision ID: 048a678e8b76
Revises: ca0da9d05a00
Create Date: 2020-03-20 00:52:50.590641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048a678e8b76'
down_revision = 'ca0da9d05a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_mapping', sa.Column('verify_cod', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_mapping', 'verify_cod')
    # ### end Alembic commands ###
