"""empty message

Revision ID: 0836f81bde11
Revises: 1ec29440e396
Create Date: 2021-04-12 20:57:33.672370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0836f81bde11'
down_revision = '1ec29440e396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloads', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downloads', 'file_size')
    # ### end Alembic commands ###
