"""empty message

Revision ID: 09cf8b022386
Revises: 5acfffa61907
Create Date: 2019-11-14 22:33:02.838893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cf8b022386'
down_revision = '5acfffa61907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_channel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_prefix', sa.String(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('api_password', sa.String(), nullable=True),
    sa.Column('shop_url', sa.String(), nullable=True),
    sa.Column('last_synced_order', sa.String(), nullable=True),
    sa.Column('last_synced_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['master_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('client_channel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'client_channel', ['client_channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'client_channel_id')
    op.drop_table('client_channel')
    # ### end Alembic commands ###
