"""empty message

Revision ID: 0c0fd80f0b33
Revises: 56df1b681e8f
Create Date: 2020-10-03 14:18:59.762836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0fd80f0b33'
down_revision = '56df1b681e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_pickups', sa.Column('wareiq_location', sa.BOOLEAN(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_pickups', 'wareiq_location')
    # ### end Alembic commands ###
