"""empty message

Revision ID: 0f97745358c6
Revises: 6ccf0bf41a1f
Create Date: 2020-01-21 00:33:40.258482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f97745358c6'
down_revision = '6ccf0bf41a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_quantity', sa.Column('current_quantity', sa.Integer(), nullable=True))
    op.add_column('products_quantity', sa.Column('inline_quantity', sa.Integer(), nullable=True))
    op.add_column('products_quantity', sa.Column('rto_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_quantity', 'rto_quantity')
    op.drop_column('products_quantity', 'inline_quantity')
    op.drop_column('products_quantity', 'current_quantity')
    # ### end Alembic commands ###
