"""empty message

Revision ID: 12e054df2cd7
Revises: 1388564500b2
Create Date: 2020-05-07 17:43:07.586593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12e054df2cd7'
down_revision = '1388564500b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_channel', sa.Column('fetch_status', postgresql.ARRAY(sa.String(length=20)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_channel', 'fetch_status')
    # ### end Alembic commands ###
