"""empty message

Revision ID: 131f9c272fc7
Revises: ea688f0bbb9d
Create Date: 2019-12-05 16:01:36.243895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131f9c272fc7'
down_revision = 'ea688f0bbb9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('tracking_link', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'tracking_link')
    # ### end Alembic commands ###
