"""empty message

Revision ID: 16b051bfbfb5
Revises: 88b3cc3b3294
Create Date: 2021-01-28 19:01:53.998524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b051bfbfb5'
down_revision = '88b3cc3b3294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op_association', sa.Column('master_product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'op_association', 'master_products', ['master_product_id'], ['id'])
    op.add_column('products_quantity', sa.Column('exception_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_quantity', 'exception_quantity')
    op.drop_constraint(None, 'op_association', type_='foreignkey')
    op.drop_column('op_association', 'master_product_id')
    # ### end Alembic commands ###
