"""empty message

Revision ID: 17dd01a6d45c
Revises: 62dd8009e846
Create Date: 2021-07-19 20:56:23.260285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17dd01a6d45c'
down_revision = '62dd8009e846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remittance_order_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('remittance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['remittance_id'], ['cod_remittance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remittance_order_map_order_id'), 'remittance_order_map', ['order_id'], unique=False)
    op.add_column('client_mapping', sa.Column('order_split_type', sa.Integer(), nullable=True))
    op.add_column('client_mapping', sa.Column('tracking_url', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'client_mapping', ['tracking_url'])
    op.add_column('master_couriers', sa.Column('api_credential_1', sa.String(), nullable=True))
    op.add_column('master_couriers', sa.Column('api_credential_2', sa.String(), nullable=True))
    op.add_column('master_couriers', sa.Column('client_code', sa.String(), nullable=True))
    op.add_column('master_couriers', sa.Column('courier_view_name', sa.String(), nullable=True))
    op.add_column('master_couriers', sa.Column('type', sa.String(), nullable=True))
    op.add_column('op_association', sa.Column('discount_amount', sa.FLOAT(), nullable=True))
    op.add_column('op_association', sa.Column('discount_code', sa.String(), nullable=True))
    op.add_column('op_association', sa.Column('discount_type', sa.String(), nullable=True))
    op.add_column('orders_payments', sa.Column('discount_amount', sa.FLOAT(), nullable=True))
    op.add_column('orders_payments', sa.Column('discount_code', sa.String(), nullable=True))
    op.add_column('orders_payments', sa.Column('discount_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_payments', 'discount_type')
    op.drop_column('orders_payments', 'discount_code')
    op.drop_column('orders_payments', 'discount_amount')
    op.drop_column('op_association', 'discount_type')
    op.drop_column('op_association', 'discount_code')
    op.drop_column('op_association', 'discount_amount')
    op.drop_column('master_couriers', 'type')
    op.drop_column('master_couriers', 'courier_view_name')
    op.drop_column('master_couriers', 'client_code')
    op.drop_column('master_couriers', 'api_credential_2')
    op.drop_column('master_couriers', 'api_credential_1')
    op.drop_constraint(None, 'client_mapping', type_='unique')
    op.drop_column('client_mapping', 'tracking_url')
    op.drop_column('client_mapping', 'order_split_type')
    op.drop_index(op.f('ix_remittance_order_map_order_id'), table_name='remittance_order_map')
    op.drop_table('remittance_order_map')
    # ### end Alembic commands ###
