"""empty message

Revision ID: 19a227b3679e
Revises: 76bfda6ac1ac
Create Date: 2019-11-23 14:23:41.655227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a227b3679e'
down_revision = '76bfda6ac1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_couriers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_prefix', sa.String(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('last_shipped_order_id', sa.Integer(), nullable=True),
    sa.Column('last_shipped_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['master_couriers.id'], ),
    sa.ForeignKeyConstraint(['last_shipped_order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('master_couriers', sa.Column('api_key', sa.String(), nullable=True))
    op.add_column('master_couriers', sa.Column('api_password', sa.String(), nullable=True))
    op.add_column('master_couriers', sa.Column('api_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_couriers', 'api_url')
    op.drop_column('master_couriers', 'api_password')
    op.drop_column('master_couriers', 'api_key')
    op.drop_table('client_couriers')
    # ### end Alembic commands ###
