"""empty message

Revision ID: 1b5befa68a1e
Revises: 0c0fd80f0b33
Create Date: 2020-10-05 22:21:52.635387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5befa68a1e'
down_revision = '0c0fd80f0b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cod_verification_order_id'), 'cod_verification', ['order_id'], unique=True)
    op.create_index(op.f('ix_ndr_shipments_order_id'), 'ndr_shipments', ['order_id'], unique=False)
    op.create_index(op.f('ix_ndr_verification_order_id'), 'ndr_verification', ['order_id'], unique=False)
    op.create_index(op.f('ix_orders_payments_order_id'), 'orders_payments', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_payments_order_id'), table_name='orders_payments')
    op.drop_index(op.f('ix_ndr_verification_order_id'), table_name='ndr_verification')
    op.drop_index(op.f('ix_ndr_shipments_order_id'), table_name='ndr_shipments')
    op.drop_index(op.f('ix_cod_verification_order_id'), table_name='cod_verification')
    # ### end Alembic commands ###
