"""empty message

Revision ID: 1d074f6f4609
Revises: 09cf8b022386
Create Date: 2019-11-19 16:16:14.651281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d074f6f4609'
down_revision = '09cf8b022386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('address_one', sa.Text(), nullable=True),
    sa.Column('address_two', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('delivery_address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'shipping_address', ['delivery_address_id'], ['id'])
    op.drop_column('orders', 'delivery_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_address', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_address_id')
    op.drop_table('shipping_address')
    # ### end Alembic commands ###
