"""updated client customization model

Revision ID: 1d776214007b
Revises: cdce758a8a31
Create Date: 2021-07-21 11:51:41.699403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d776214007b'
down_revision = 'cdce758a8a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'client_customization', ['subdomain'])
    op.create_unique_constraint(None, 'client_customization', ['client_prefix'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_customization', type_='unique')
    op.drop_constraint(None, 'client_customization', type_='unique')
    # ### end Alembic commands ###
