"""empty message

Revision ID: 1ec29440e396
Revises: e685fe5e17b9
Create Date: 2021-04-12 14:54:30.814304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec29440e396'
down_revision = 'e685fe5e17b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_prefix', sa.String(), nullable=True),
    sa.Column('client_prefix', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('download_link', sa.String(), nullable=True),
    sa.Column('dl_from', sa.DateTime(), nullable=True),
    sa.Column('dl_to', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('downloads')
    # ### end Alembic commands ###
