"""empty message

Revision ID: 1f82f485d255
Revises: 7e7f48d2992c
Create Date: 2020-06-18 21:23:34.208595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f82f485d255'
down_revision = '7e7f48d2992c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_mapping', sa.Column('hide_weights', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_mapping', 'hide_weights')
    # ### end Alembic commands ###
