"""empty message

Revision ID: 1fa0713b7d0b
Revises: 824b05e998c6
Create Date: 2021-05-24 22:57:56.389504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa0713b7d0b'
down_revision = '824b05e998c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhooks', sa.Column('fail_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhooks', 'fail_count')
    # ### end Alembic commands ###
