"""empty message

Revision ID: 23aa6ccc47ba
Revises: 75840be9cd07
Create Date: 2020-10-02 15:47:36.535728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23aa6ccc47ba'
down_revision = '75840be9cd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_mapping', sa.Column('auto_pur', sa.BOOLEAN(), nullable=True))
    op.add_column('client_mapping', sa.Column('auto_pur_time', sa.Integer(), nullable=True))
    op.drop_column('manifests', 'auto_pur')
    op.drop_column('manifests', 'auto_pur_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manifests', sa.Column('auto_pur_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('manifests', sa.Column('auto_pur', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('client_mapping', 'auto_pur_time')
    op.drop_column('client_mapping', 'auto_pur')
    # ### end Alembic commands ###
