"""empty message

Revision ID: 26cd25883a21
Revises: 683f34a6605e
Create Date: 2020-04-07 19:44:21.743165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26cd25883a21'
down_revision = '683f34a6605e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manifests', sa.Column('client_pickup_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'manifests', 'client_pickups', ['client_pickup_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manifests', type_='foreignkey')
    op.drop_column('manifests', 'client_pickup_id')
    # ### end Alembic commands ###
