"""empty message

Revision ID: 28e51083a583
Revises: b7add52829ca
Create Date: 2019-11-12 16:12:27.731148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e51083a583'
down_revision = 'b7add52829ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op_association', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_primary_key('op_association_pkey', 'op_association', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('op_association', 'id')
    # ### end Alembic commands ###
