"""empty message

Revision ID: 2d5ab83d4d5a
Revises: 80d9a2ecc307
Create Date: 2020-07-15 00:27:08.950056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5ab83d4d5a'
down_revision = '80d9a2ecc307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('chargeable_weight', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'chargeable_weight')
    # ### end Alembic commands ###
