"""empty message

Revision ID: 2e6d0d4684aa
Revises: bea0c8af00c5
Create Date: 2020-01-22 01:14:23.461441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6d0d4684aa'
down_revision = 'bea0c8af00c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cod_verification', sa.Column('verification_link', sa.String(), nullable=True))
    op.add_column('cod_verification', sa.Column('verification_time', sa.DateTime(), nullable=True))
    op.add_column('cod_verification', sa.Column('verified_via', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cod_verification', 'verified_via')
    op.drop_column('cod_verification', 'verification_time')
    op.drop_column('cod_verification', 'verification_link')
    # ### end Alembic commands ###
