"""empty message

Revision ID: 356d5ccd46a1
Revises: 1b5befa68a1e
Create Date: 2020-10-06 00:15:12.452489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356d5ccd46a1'
down_revision = '1b5befa68a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_op_association_order_id'), 'op_association', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_op_association_order_id'), table_name='op_association')
    # ### end Alembic commands ###
