"""empty message

Revision ID: 3658dd35aabc
Revises: 00edd95f0925
Create Date: 2019-11-24 19:06:24.139451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3658dd35aabc'
down_revision = '00edd95f0925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('remark', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'remark')
    # ### end Alembic commands ###
