"""empty message

Revision ID: 37be8331daf2
Revises: c7fd3d33300f
Create Date: 2020-09-24 01:07:27.678004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37be8331daf2'
down_revision = 'c7fd3d33300f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_pickups', sa.Column('active', sa.BOOLEAN(), server_default="true", nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_pickups', 'active')
    # ### end Alembic commands ###
