"""empty message

Revision ID: 38b4f1647278
Revises: 6bf68ccacf1a
Create Date: 2019-11-27 17:40:05.340757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b4f1647278'
down_revision = '6bf68ccacf1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manifests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manifest_id', sa.String(), nullable=False),
    sa.Column('warehouse_prefix', sa.String(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('pickup_id', sa.Integer(), nullable=True),
    sa.Column('no_of_orders', sa.Integer(), nullable=False),
    sa.Column('pickup_date', sa.DateTime(), nullable=True),
    sa.Column('manifest_url', sa.TEXT(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['master_couriers.id'], ),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickup_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickup_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_prefix', sa.String(), nullable=False),
    sa.Column('warehouse_prefix', sa.String(), nullable=False),
    sa.Column('last_picked_order_id', sa.Integer(), nullable=True),
    sa.Column('pickup_after_hours', sa.Integer(), nullable=False),
    sa.Column('last_pickup_request_date', sa.DateTime(), nullable=True),
    sa.Column('pickup_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['last_picked_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickup_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pickup_requests')
    op.drop_table('manifests')
    # ### end Alembic commands ###
