"""empty message

Revision ID: 38c25acb7f18
Revises: 3658dd35aabc
Create Date: 2019-11-26 15:42:21.523864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c25acb7f18'
down_revision = '3658dd35aabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pickup_location', sa.Text(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('address_two', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.Column('warehouse_prefix', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client_pickups', sa.Column('return_point_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_pickups', 'return_points', ['return_point_id'], ['id'])
    op.add_column('shipments', sa.Column('return_point_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shipments', 'return_points', ['return_point_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'return_point_id')
    op.drop_constraint(None, 'client_pickups', type_='foreignkey')
    op.drop_column('client_pickups', 'return_point_id')
    op.drop_table('return_points')
    # ### end Alembic commands ###
