"""empty message

Revision ID: 3ded99f21bc6
Revises: 51c5b3e84c36
Create Date: 2020-03-11 19:18:02.948382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ded99f21bc6'
down_revision = '51c5b3e84c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier_charges', sa.Column('shipment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courier_charges', 'shipments', ['shipment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courier_charges', type_='foreignkey')
    op.drop_column('courier_charges', 'shipment_id')
    # ### end Alembic commands ###
