"""empty message

Revision ID: 3e5fbb4b58ef
Revises: 1d776214007b
Create Date: 2021-07-29 16:05:09.745653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e5fbb4b58ef'
down_revision = '1d776214007b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_customization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_prefix', sa.String(), nullable=False),
    sa.Column('subdomain', sa.String(), nullable=True),
    sa.Column('client_logo_url', sa.String(), nullable=True),
    sa.Column('theme_color', sa.String(), nullable=True),
    sa.Column('background_image_url', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_url', sa.String(), nullable=True),
    sa.Column('nav_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('support_url', sa.String(), nullable=True),
    sa.Column('privacy_url', sa.String(), nullable=True),
    sa.Column('nps_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('banners', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_prefix'),
    sa.UniqueConstraint('subdomain')
    )
    op.drop_table('shipping_rules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_prefix', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rule_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('courier_1_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('courier_2_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('courier_3_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('courier_4_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['courier_1_id'], ['master_couriers.id'], name='shipping_rules_courier_1_id_fkey'),
    sa.ForeignKeyConstraint(['courier_2_id'], ['master_couriers.id'], name='shipping_rules_courier_2_id_fkey'),
    sa.ForeignKeyConstraint(['courier_3_id'], ['master_couriers.id'], name='shipping_rules_courier_3_id_fkey'),
    sa.ForeignKeyConstraint(['courier_4_id'], ['master_couriers.id'], name='shipping_rules_courier_4_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shipping_rules_pkey')
    )
    op.drop_table('client_customization')
    # ### end Alembic commands ###
