"""empty message

Revision ID: 3ebfc396ddff
Revises: 6592cf89a518
Create Date: 2020-09-16 17:49:44.920005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ebfc396ddff'
down_revision = '6592cf89a518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_channel', sa.Column('shared_secret', sa.String(), nullable=True))
    op.add_column('client_channel', sa.Column('store_name', sa.String(), nullable=True))
    op.add_column('client_channel', sa.Column('sync_inventory', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_channel', 'sync_inventory')
    op.drop_column('client_channel', 'store_name')
    op.drop_column('client_channel', 'shared_secret')
    # ### end Alembic commands ###
