"""empty message

Revision ID: 3f7727c46790
Revises: 5ef39d266651
Create Date: 2020-11-02 13:07:12.183256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7727c46790'
down_revision = '5ef39d266651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cod_remittance', sa.Column('mode', sa.String(), nullable=True))
    op.add_column('cod_remittance', sa.Column('payout_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cod_remittance', 'payout_id')
    op.drop_column('cod_remittance', 'mode')
    # ### end Alembic commands ###
