"""empty message

Revision ID: 43cf9eea4004
Revises: e5b1b95bf76d
Create Date: 2021-01-14 02:43:53.821074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cf9eea4004'
down_revision = 'e5b1b95bf76d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_invoice_order_id', table_name='orders_invoice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_invoice_order_id', 'orders_invoice', ['order_id'], unique=True)
    # ### end Alembic commands ###
