"""empty message

Revision ID: 455433f7ab0c
Revises: e6f90b577ace
Create Date: 2020-06-07 19:13:54.480484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455433f7ab0c'
down_revision = 'e6f90b577ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_mapping', sa.Column('unique_parameter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_mapping', 'unique_parameter')
    # ### end Alembic commands ###
