"""empty message

Revision ID: 47f1ee30ca8d
Revises: 7c1eb12e9bb0
Create Date: 2020-04-01 20:16:28.845888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f1ee30ca8d'
down_revision = '7c1eb12e9bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_couriers', sa.Column('active', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_couriers', 'active')
    # ### end Alembic commands ###
