"""empty message

Revision ID: 48fbd9bfd370
Revises: 887030feaaf4
Create Date: 2020-05-10 12:49:52.976825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fbd9bfd370'
down_revision = '887030feaaf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op_association', sa.Column('channel_item_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('op_association', 'channel_item_id')
    # ### end Alembic commands ###
