"""empty message

Revision ID: 5051c12546c0
Revises: cb1fa3e6e35c
Create Date: 2021-02-09 17:07:08.720177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5051c12546c0'
down_revision = 'cb1fa3e6e35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_ro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_prefix', sa.String(), nullable=False),
    sa.Column('client_prefix', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('no_of_boxes', sa.Integer(), nullable=True),
    sa.Column('tracking_details', sa.String(), nullable=True),
    sa.Column('edd', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_wro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wro_id', sa.Integer(), nullable=True),
    sa.Column('master_product_id', sa.Integer(), nullable=True),
    sa.Column('ro_quantity', sa.Integer(), nullable=True),
    sa.Column('received_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.ForeignKeyConstraint(['wro_id'], ['warehouse_ro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_wro_wro_id'), 'products_wro', ['wro_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_wro_wro_id'), table_name='products_wro')
    op.drop_table('products_wro')
    op.drop_table('warehouse_ro')
    # ### end Alembic commands ###
