"""empty message

Revision ID: 51c5b3e84c36
Revises: d3f99f513f27
Create Date: 2020-03-11 19:14:29.227370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c5b3e84c36'
down_revision = 'd3f99f513f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courier_charges_shipment_id_fkey', 'courier_charges', type_='foreignkey')
    op.drop_column('courier_charges', 'shipment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier_charges', sa.Column('shipment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('courier_charges_shipment_id_fkey', 'courier_charges', 'shipments', ['shipment_id'], ['id'])
    # ### end Alembic commands ###
