"""empty message

Revision ID: 521c8b3c87e8
Revises: a9a4b0a94629
Create Date: 2020-10-16 00:16:48.319937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521c8b3c87e8'
down_revision = 'a9a4b0a94629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_deductions', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_deductions', 'type')
    # ### end Alembic commands ###
