"""empty message

Revision ID: 5587bfa662d9
Revises: 48fbd9bfd370
Create Date: 2020-05-16 17:40:50.788874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5587bfa662d9'
down_revision = '48fbd9bfd370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_combos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('combo_id', sa.Integer(), nullable=True),
    sa.Column('combo_prod_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['combo_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['combo_prod_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_combos')
    # ### end Alembic commands ###
