"""empty message

Revision ID: 59412dd2010e
Revises: 0c4a4f17ec71
Create Date: 2020-05-24 14:42:48.831634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59412dd2010e'
down_revision = '0c4a4f17ec71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ndr_shipments', sa.Column('current_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ndr_shipments', 'current_status')
    # ### end Alembic commands ###
