"""empty message

Revision ID: 5b4448d3ee80
Revises: 53e068a04cd5
Create Date: 2019-11-08 19:52:01.297206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b4448d3ee80'
down_revision = '53e068a04cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_quantity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('approved_quantity', sa.Integer(), nullable=True),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('warehouse_prefix', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('active', sa.BOOLEAN(), nullable=True))
    op.add_column('products', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('client_prefix', sa.String(), nullable=True))
    op.add_column('products', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('dimensions', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('price', sa.FLOAT(), nullable=True))
    op.add_column('products', sa.Column('product_image', sa.String(), nullable=True))
    op.add_column('products', sa.Column('weight', sa.FLOAT(), nullable=True))
    op.create_foreign_key(None, 'products', 'master_channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'product_image')
    op.drop_column('products', 'price')
    op.drop_column('products', 'dimensions')
    op.drop_column('products', 'date_updated')
    op.drop_column('products', 'date_created')
    op.drop_column('products', 'client_prefix')
    op.drop_column('products', 'channel_id')
    op.drop_column('products', 'active')
    op.drop_table('products_quantity')
    op.drop_table('master_channels')
    # ### end Alembic commands ###
