"""empty message

Revision ID: 5e82ce459e5a
Revises: 1d074f6f4609
Create Date: 2019-11-22 11:58:58.467531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e82ce459e5a'
down_revision = '1d074f6f4609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_payments', sa.Column('shipping_charges', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_payments', 'shipping_charges')
    # ### end Alembic commands ###
