"""empty message

Revision ID: 5ef39d266651
Revises: 6c2d9ebdddd7
Create Date: 2020-10-26 19:37:02.919097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef39d266651'
down_revision = '6c2d9ebdddd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_recharges', sa.Column('code', sa.String(), nullable=True))
    op.add_column('client_recharges', sa.Column('description', sa.String(), nullable=True))
    op.add_column('client_recharges', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('client_recharges', sa.Column('signature', sa.String(), nullable=True))
    op.add_column('client_recharges', sa.Column('source', sa.String(), nullable=True))
    op.add_column('client_recharges', sa.Column('step', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_recharges', 'step')
    op.drop_column('client_recharges', 'source')
    op.drop_column('client_recharges', 'signature')
    op.drop_column('client_recharges', 'reason')
    op.drop_column('client_recharges', 'description')
    op.drop_column('client_recharges', 'code')
    # ### end Alembic commands ###
