"""empty message

Revision ID: 61eaaf219f64
Revises: 04712497f469
Create Date: 2020-03-06 19:22:11.609063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61eaaf219f64'
down_revision = '04712497f469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('master_sku', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'master_sku')
    # ### end Alembic commands ###
