"""empty message

Revision ID: 62dd8009e846
Revises: b27f24715f49
Create Date: 2021-06-01 16:43:07.417832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62dd8009e846'
down_revision = 'b27f24715f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pincode_serviceability', sa.Column('sortcode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pincode_serviceability', 'sortcode')
    # ### end Alembic commands ###
