"""empty message

Revision ID: 6592cf89a518
Revises: e4ca349f84f2
Create Date: 2020-09-13 21:19:44.882339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6592cf89a518'
down_revision = 'e4ca349f84f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('pdd', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'pdd')
    # ### end Alembic commands ###
