"""empty message

Revision ID: 68095d1f8c05
Revises: cfa5b317e4be
Create Date: 2020-12-29 23:37:30.054962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68095d1f8c05'
down_revision = 'cfa5b317e4be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discrepency_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weight_discrepency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('raised_date', sa.DateTime(), nullable=True),
    sa.Column('dispute_date', sa.DateTime(), nullable=True),
    sa.Column('charged_weight', sa.FLOAT(), nullable=True),
    sa.Column('expected_amount', sa.FLOAT(), nullable=True),
    sa.Column('charged_amount', sa.FLOAT(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['discrepency_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client_mapping', sa.Column('remittance_cycle', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_mapping', 'remittance_cycle')
    op.drop_table('weight_discrepency')
    op.drop_table('discrepency_status')
    # ### end Alembic commands ###
