"""empty message

Revision ID: 683f34a6605e
Revises: 47f1ee30ca8d
Create Date: 2020-04-06 03:15:00.033080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683f34a6605e'
down_revision = '47f1ee30ca8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op_association', sa.Column('amount', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('op_association', 'amount')
    # ### end Alembic commands ###
