"""empty message

Revision ID: 6993885f46f5
Revises: 6147c5aa58c9
Create Date: 2020-12-10 21:13:30.814559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6993885f46f5'
down_revision = '6147c5aa58c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_pickups', sa.Column('easyecom_loc_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('master_channel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'master_channels', ['master_channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'master_channel_id')
    op.drop_column('client_pickups', 'easyecom_loc_code')
    # ### end Alembic commands ###
