"""empty message

Revision ID: 6b7281ed9067
Revises: 6f9da85d1fa5
Create Date: 2019-12-23 14:33:26.705113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7281ed9067'
down_revision = '6f9da85d1fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('id_client_unique', 'orders', ['channel_order_id', 'client_prefix'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('id_client_unique', 'orders', type_='unique')
    # ### end Alembic commands ###
