"""empty message

Revision ID: 6b75521fdff0
Revises: 3ebfc396ddff
Create Date: 2020-09-17 20:33:58.228790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b75521fdff0'
down_revision = '3ebfc396ddff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_channel', sa.Column('connection_status', sa.BOOLEAN(), server_default='true', nullable=False))
    op.add_column('client_channel', sa.Column('status', sa.BOOLEAN(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_channel', 'status')
    op.drop_column('client_channel', 'connection_status')
    # ### end Alembic commands ###
