"""empty message

Revision ID: 6bf68ccacf1a
Revises: 38c25acb7f18
Create Date: 2019-11-26 15:58:21.029268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf68ccacf1a'
down_revision = '38c25acb7f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_points', sa.Column('return_location', sa.Text(), nullable=True))
    op.drop_column('return_points', 'pickup_location')
    op.add_column('shipments', sa.Column('routing_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'routing_code')
    op.add_column('return_points', sa.Column('pickup_location', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('return_points', 'return_location')
    # ### end Alembic commands ###
