"""empty message

Revision ID: 6c2d9ebdddd7
Revises: 521c8b3c87e8
Create Date: 2020-10-19 22:59:19.100784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2d9ebdddd7'
down_revision = '521c8b3c87e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_mapping', sa.Column('account_type', sa.String(), nullable=True))
    op.add_column('client_mapping', sa.Column('current_balance', sa.FLOAT(), nullable=False, server_default="0.0"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_mapping', 'current_balance')
    op.drop_column('client_mapping', 'account_type')
    # ### end Alembic commands ###
