"""empty message

Revision ID: 6ccf0bf41a1f
Revises: 0420fd51d95f
Create Date: 2020-01-12 23:32:41.927120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ccf0bf41a1f'
down_revision = '0420fd51d95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_recharges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_prefix', sa.String(), nullable=True),
    sa.Column('recharge_amount', sa.FLOAT(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('bank_transaction_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('recharge_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_deductions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_prefix', sa.String(), nullable=True),
    sa.Column('deducted_amount', sa.FLOAT(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('weight_charged', sa.FLOAT(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('deduction_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_deductions')
    op.drop_table('client_recharges')
    # ### end Alembic commands ###
