"""empty message

Revision ID: 7083c6a7babd
Revises: 97cd4621cd71
Create Date: 2020-02-01 13:46:56.168488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7083c6a7babd'
down_revision = '97cd4621cd71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_deductions', sa.Column('cod_charge', sa.FLOAT(), nullable=True))
    op.add_column('client_deductions', sa.Column('cod_charged_gst', sa.FLOAT(), nullable=True))
    op.add_column('client_deductions', sa.Column('forward_charge', sa.FLOAT(), nullable=True))
    op.add_column('client_deductions', sa.Column('forward_charge_gst', sa.FLOAT(), nullable=True))
    op.add_column('client_deductions', sa.Column('rto_charge', sa.FLOAT(), nullable=True))
    op.add_column('client_deductions', sa.Column('rto_charge_gst', sa.FLOAT(), nullable=True))
    op.add_column('client_deductions', sa.Column('shipment_id', sa.Integer(), nullable=True))
    op.add_column('client_deductions', sa.Column('total_charge', sa.FLOAT(), nullable=True))
    op.add_column('client_deductions', sa.Column('total_charged_gst', sa.FLOAT(), nullable=True))
    op.drop_constraint('client_deductions_order_id_fkey', 'client_deductions', type_='foreignkey')
    op.create_foreign_key(None, 'client_deductions', 'shipments', ['shipment_id'], ['id'])
    op.drop_column('client_deductions', 'deducted_amount')
    op.drop_column('client_deductions', 'client_prefix')
    op.drop_column('client_deductions', 'status')
    op.drop_column('client_deductions', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_deductions', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('client_deductions', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('client_deductions', sa.Column('client_prefix', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('client_deductions', sa.Column('deducted_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'client_deductions', type_='foreignkey')
    op.create_foreign_key('client_deductions_order_id_fkey', 'client_deductions', 'orders', ['order_id'], ['id'])
    op.drop_column('client_deductions', 'total_charged_gst')
    op.drop_column('client_deductions', 'total_charge')
    op.drop_column('client_deductions', 'shipment_id')
    op.drop_column('client_deductions', 'rto_charge_gst')
    op.drop_column('client_deductions', 'rto_charge')
    op.drop_column('client_deductions', 'forward_charge_gst')
    op.drop_column('client_deductions', 'forward_charge')
    op.drop_column('client_deductions', 'cod_charged_gst')
    op.drop_column('client_deductions', 'cod_charge')
    # ### end Alembic commands ###
