"""empty message

Revision ID: 7527c46ad20c
Revises: 6b7281ed9067
Create Date: 2020-01-03 22:38:01.954610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7527c46ad20c'
down_revision = '6b7281ed9067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_status', sa.Column('shipment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_status', 'shipments', ['shipment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_status', type_='foreignkey')
    op.drop_column('order_status', 'shipment_id')
    # ### end Alembic commands ###
