"""empty message

Revision ID: 75840be9cd07
Revises: 37be8331daf2
Create Date: 2020-10-02 15:28:28.988011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75840be9cd07'
down_revision = '37be8331daf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_pickups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manifest_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('picked', sa.BOOLEAN(), nullable=True),
    sa.Column('pickup_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manifest_id'], ['manifests.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'manifest_id', name='ord_mnf_unique')
    )
    op.drop_index('client_channel_idx_id', table_name='client_channel')
    op.drop_index('client_pickups_idx_id', table_name='client_pickups')
    op.drop_index('cod_verification_idx_order_id', table_name='cod_verification')
    op.add_column('cost_to_clients', sa.Column('a_step', sa.FLOAT(), nullable=True))
    op.add_column('cost_to_clients', sa.Column('b_step', sa.FLOAT(), nullable=True))
    op.add_column('cost_to_clients', sa.Column('c_step', sa.FLOAT(), nullable=True))
    op.add_column('cost_to_clients', sa.Column('d_step', sa.FLOAT(), nullable=True))
    op.add_column('cost_to_clients', sa.Column('e_step', sa.FLOAT(), nullable=True))
    op.add_column('cost_to_clients', sa.Column('rvp_ratio', sa.FLOAT(), nullable=True))
    op.add_column('manifests', sa.Column('auto_pur', sa.BOOLEAN(), nullable=True))
    op.add_column('manifests', sa.Column('auto_pur_time', sa.Integer(), nullable=True))
    op.drop_index('master_channels_idx_id', table_name='master_channels')
    op.drop_index('master_couriers_idx_id', table_name='master_couriers')
    op.drop_index('ndr_reasons_idx_id', table_name='ndr_reasons')
    op.drop_index('ndr_verification_idx_order_id', table_name='ndr_verification')
    op.drop_index('op_association_idx_order_id', table_name='op_association')
    op.drop_index('ord_cr_shp_st_sttime_unique', table_name='order_scans')
    op.create_unique_constraint('ord_cr_shp_st_sttime_unique', 'order_scans', ['order_id', 'courier_id', 'shipment_id', 'status', 'status_time'])
    op.drop_index('ord_cr_shp_st_unique', table_name='order_status')
    op.create_unique_constraint('ord_cr_shp_st_unique', 'order_status', ['order_id', 'courier_id', 'shipment_id', 'status'])
    op.drop_index('order_status_idx_status_order_id', table_name='order_status')
    op.drop_index('orders_id_date_idx', table_name='orders')
    op.drop_index('orders_idx_order_date_id', table_name='orders')
    op.drop_index('orders_payments_idx_order_id', table_name='orders_payments')
    op.drop_index('pickup_points_idx_id', table_name='pickup_points')
    op.drop_index('products_idx_id', table_name='products')
    op.add_column('shipments', sa.Column('zone', sa.String(), nullable=True))
    op.drop_index('shipments_idx_order_id', table_name='shipments')
    op.drop_index('shipping_address_idx_id', table_name='shipping_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('shipping_address_idx_id', 'shipping_address', ['id'], unique=False)
    op.create_index('shipments_idx_order_id', 'shipments', ['order_id'], unique=False)
    op.drop_column('shipments', 'zone')
    op.create_index('products_idx_id', 'products', ['id'], unique=False)
    op.create_index('pickup_points_idx_id', 'pickup_points', ['id'], unique=False)
    op.create_index('orders_payments_idx_order_id', 'orders_payments', ['order_id'], unique=False)
    op.create_index('orders_idx_order_date_id', 'orders', ['order_date', 'id'], unique=False)
    op.create_index('orders_id_date_idx', 'orders', ['order_date', 'id'], unique=False)
    op.create_index('order_status_idx_status_order_id', 'order_status', ['status', 'order_id'], unique=False)
    op.drop_constraint('ord_cr_shp_st_unique', 'order_status', type_='unique')
    op.create_index('ord_cr_shp_st_unique', 'order_status', ['order_id', 'courier_id', 'shipment_id', 'status'], unique=True)
    op.drop_constraint('ord_cr_shp_st_sttime_unique', 'order_scans', type_='unique')
    op.create_index('ord_cr_shp_st_sttime_unique', 'order_scans', ['order_id', 'courier_id', 'shipment_id', 'status', 'status_time'], unique=True)
    op.create_index('op_association_idx_order_id', 'op_association', ['order_id'], unique=False)
    op.create_index('ndr_verification_idx_order_id', 'ndr_verification', ['order_id'], unique=False)
    op.create_index('ndr_reasons_idx_id', 'ndr_reasons', ['id'], unique=False)
    op.create_index('master_couriers_idx_id', 'master_couriers', ['id'], unique=False)
    op.create_index('master_channels_idx_id', 'master_channels', ['id'], unique=False)
    op.drop_column('manifests', 'auto_pur_time')
    op.drop_column('manifests', 'auto_pur')
    op.drop_column('cost_to_clients', 'rvp_ratio')
    op.drop_column('cost_to_clients', 'e_step')
    op.drop_column('cost_to_clients', 'd_step')
    op.drop_column('cost_to_clients', 'c_step')
    op.drop_column('cost_to_clients', 'b_step')
    op.drop_column('cost_to_clients', 'a_step')
    op.create_index('cod_verification_idx_order_id', 'cod_verification', ['order_id'], unique=False)
    op.create_index('client_pickups_idx_id', 'client_pickups', ['id'], unique=False)
    op.create_index('client_channel_idx_id', 'client_channel', ['id'], unique=False)
    op.drop_table('order_pickups')
    # ### end Alembic commands ###
