"""empty message

Revision ID: 76c3b6017336
Revises: ade16cd4b4f9
Create Date: 2020-03-14 14:09:29.633654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c3b6017336'
down_revision = 'ade16cd4b4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_mapping', sa.Column('client_logo', sa.String(), nullable=True))
    op.add_column('client_mapping', sa.Column('theme_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_mapping', 'theme_color')
    op.drop_column('client_mapping', 'client_logo')
    # ### end Alembic commands ###
