"""empty message

Revision ID: 7c1eb12e9bb0
Revises: 048a678e8b76
Create Date: 2020-03-21 14:47:13.451683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1eb12e9bb0'
down_revision = '048a678e8b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_mapping', sa.Column('custom_email', sa.Text(), nullable=True))
    op.add_column('client_mapping', sa.Column('custom_email_subject', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_mapping', 'custom_email_subject')
    op.drop_column('client_mapping', 'custom_email')
    # ### end Alembic commands ###
