"""empty message

Revision ID: 7e7f48d2992c
Revises: 455433f7ab0c
Create Date: 2020-06-09 09:04:17.393751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7f48d2992c'
down_revision = '455433f7ab0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_mapping', sa.Column('cod_ship_unconfirmed', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_mapping', 'cod_ship_unconfirmed')
    # ### end Alembic commands ###
