"""empty message

Revision ID: 80d9a2ecc307
Revises: f4a0870df09b
Create Date: 2020-07-11 00:25:38.150225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d9a2ecc307'
down_revision = 'f4a0870df09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_mapping', sa.Column('default_warehouse', sa.String(), nullable=True))
    op.add_column('client_mapping', sa.Column('order_split', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_mapping', 'order_split')
    op.drop_column('client_mapping', 'default_warehouse')
    # ### end Alembic commands ###
