"""empty message

Revision ID: 824b05e998c6
Revises: a7b391ebce73
Create Date: 2021-05-24 22:36:40.525352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824b05e998c6'
down_revision = 'a7b391ebce73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_prefix', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('webhook_name', sa.String(), nullable=True),
    sa.Column('header_key', sa.String(), nullable=True),
    sa.Column('header_value', sa.String(), nullable=True),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhooks')
    # ### end Alembic commands ###
