"""empty message

Revision ID: 852c636aad18
Revises: 1fa0713b7d0b
Create Date: 2021-05-26 15:38:05.094606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852c636aad18'
down_revision = '1fa0713b7d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_passbook',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_prefix', sa.String(), nullable=False),
    sa.Column('credit', sa.FLOAT(), nullable=False),
    sa.Column('debit', sa.FLOAT(), nullable=False),
    sa.Column('closing_balance', sa.FLOAT(), nullable=True),
    sa.Column('ref_no', sa.String(), nullable=True),
    sa.Column('descr', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('txn_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_passbook')
    # ### end Alembic commands ###
