"""empty message

Revision ID: 8666d37af88a
Revises: 8b2f36eab182
Create Date: 2021-05-30 19:02:06.058041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8666d37af88a'
down_revision = '8b2f36eab182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'url_shortner', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url_shortner', type_='unique')
    # ### end Alembic commands ###
