"""empty message

Revision ID: 887030feaaf4
Revises: 12e054df2cd7
Create Date: 2020-05-08 17:34:21.498648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887030feaaf4'
down_revision = '12e054df2cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_prefix', sa.String(), nullable=False),
    sa.Column('shiplabel_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse_mapping')
    # ### end Alembic commands ###
