"""empty message

Revision ID: 88b3cc3b3294
Revises: 501b695f6b9b
Create Date: 2021-01-28 14:14:13.564281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b3cc3b3294'
down_revision = '501b695f6b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_quantity_product_id_fkey', 'products_quantity', type_='foreignkey')
    op.create_foreign_key(None, 'products_quantity', 'master_products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products_quantity', type_='foreignkey')
    op.create_foreign_key('products_quantity_product_id_fkey', 'products_quantity', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
