"""empty message

Revision ID: 8a5e2578555b
Revises: 26cd25883a21
Create Date: 2020-04-10 19:59:06.943606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5e2578555b'
down_revision = '26cd25883a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_couriers', sa.Column('integrated', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_couriers', 'integrated')
    # ### end Alembic commands ###
