"""empty message

Revision ID: 8bef6d08a705
Revises: 28e51083a583
Create Date: 2019-11-12 16:24:01.696369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bef6d08a705'
down_revision = '28e51083a583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('op_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('op_association',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='op_association_order_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='op_association_product_id_fkey')
    )
    # ### end Alembic commands ###
