"""empty message

Revision ID: 8dc4c08963f7
Revises: efe4dcf0e77b
Create Date: 2020-08-12 16:21:29.090965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc4c08963f7'
down_revision = 'efe4dcf0e77b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ivr_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('call_sid', sa.String(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('call_time', sa.DateTime(), nullable=True),
    sa.Column('from_no', sa.String(), nullable=True),
    sa.Column('to_no', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('orders_id_date_idx', table_name='orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('orders_id_date_idx', 'orders', ['order_date', 'id'], unique=False)
    op.drop_table('ivr_history')
    # ### end Alembic commands ###
