"""Added return qc table

Revision ID: 91e29afdd0f2
Revises: 3e5fbb4b58ef
Create Date: 2021-08-09 12:21:15.292310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91e29afdd0f2'
down_revision = '3e5fbb4b58ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_prefix', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('condition_type', sa.String(), nullable=False),
    sa.Column('conditions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('courier_1_id', sa.Integer(), nullable=True),
    sa.Column('courier_2_id', sa.Integer(), nullable=True),
    sa.Column('courier_3_id', sa.Integer(), nullable=True),
    sa.Column('courier_4_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courier_1_id'], ['master_couriers.id'], ),
    sa.ForeignKeyConstraint(['courier_2_id'], ['master_couriers.id'], ),
    sa.ForeignKeyConstraint(['courier_3_id'], ['master_couriers.id'], ),
    sa.ForeignKeyConstraint(['courier_4_id'], ['master_couriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return_order_quality_check',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('master_product_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('unique_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_order_quality_check_order_id'), 'return_order_quality_check', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_return_order_quality_check_order_id'), table_name='return_order_quality_check')
    op.drop_table('return_order_quality_check')
    op.drop_table('shipping_rules')
    # ### end Alembic commands ###
