"""empty message

Revision ID: 96dfc9bfb1f9
Revises: a6fc9575e76b
Create Date: 2021-03-06 17:05:28.913146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96dfc9bfb1f9'
down_revision = 'a6fc9575e76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pincode_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pincode', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('shipments', sa.Column('same_state', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'same_state')
    op.drop_table('pincode_mapping')
    # ### end Alembic commands ###
