"""empty message

Revision ID: 97cd4621cd71
Revises: 7b4a35bc2031
Create Date: 2020-01-31 19:16:23.530980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cd4621cd71'
down_revision = '7b4a35bc2031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_prefix', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_mapping')
    # ### end Alembic commands ###
