"""empty message

Revision ID: 986585043f1a
Revises: 2e6d0d4684aa
Create Date: 2020-01-22 13:10:17.376635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986585043f1a'
down_revision = '2e6d0d4684aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ndr_verification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('call_sid', sa.String(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('ndr_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('verified_via', sa.String(), nullable=True),
    sa.Column('verification_link', sa.String(), nullable=True),
    sa.Column('verification_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cod_verification', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cod_verification', 'date_created')
    op.drop_table('ndr_verification')
    # ### end Alembic commands ###
