"""empty message

Revision ID: 9e13a00bf121
Revises: 356d5ccd46a1
Create Date: 2020-10-08 14:30:37.263360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e13a00bf121'
down_revision = '356d5ccd46a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_couriers', sa.Column('additional_weight_offset', sa.FLOAT(), server_default='0.0', nullable=True))
    op.add_column('master_couriers', sa.Column('weight_offset', sa.FLOAT(), server_default='0.0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_couriers', 'weight_offset')
    op.drop_column('master_couriers', 'additional_weight_offset')
    # ### end Alembic commands ###
