"""empty message

Revision ID: 9fd0cac0bdce
Revises: 577ca54f9c15
Create Date: 2021-05-23 14:28:42.839760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd0cac0bdce'
down_revision = '577ca54f9c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickup_points', sa.Column('latitude', sa.FLOAT(), nullable=True))
    op.add_column('pickup_points', sa.Column('longitude', sa.FLOAT(), nullable=True))
    op.add_column('return_points', sa.Column('latitude', sa.FLOAT(), nullable=True))
    op.add_column('return_points', sa.Column('longitude', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_points', 'longitude')
    op.drop_column('return_points', 'latitude')
    op.drop_column('pickup_points', 'longitude')
    op.drop_column('pickup_points', 'latitude')
    # ### end Alembic commands ###
