"""empty message

Revision ID: a6c4dbd85bf9
Revises: f89b99319494
Create Date: 2020-11-03 22:36:58.078558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6c4dbd85bf9'
down_revision = 'f89b99319494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thirdwatch_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('order_timestamp', sa.String(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('reasons', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thirdwatch_data_order_id'), 'thirdwatch_data', ['order_id'], unique=True)
    op.add_column('cost_to_clients', sa.Column('management_fee_static', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost_to_clients', 'management_fee_static')
    op.drop_index(op.f('ix_thirdwatch_data_order_id'), table_name='thirdwatch_data')
    op.drop_table('thirdwatch_data')
    # ### end Alembic commands ###
