"""empty message

Revision ID: a6fc9575e76b
Revises: 201f2b4c0a89
Create Date: 2021-03-02 16:23:39.099066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fc9575e76b'
down_revision = '201f2b4c0a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_mapping', sa.Column('legal_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_mapping', 'legal_name')
    # ### end Alembic commands ###
