"""empty message

Revision ID: aadbbde56dae
Revises: 8dc4c08963f7
Create Date: 2020-08-31 13:59:08.890772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadbbde56dae'
down_revision = '8dc4c08963f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_mapping', sa.Column('hide_address', sa.BOOLEAN(), nullable=True))
    op.add_column('client_mapping', sa.Column('hide_products', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_mapping', 'hide_products')
    op.drop_column('client_mapping', 'hide_address')
    # ### end Alembic commands ###
