"""empty message

Revision ID: ade16cd4b4f9
Revises: baeecd787e41
Create Date: 2020-03-13 16:13:23.540764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade16cd4b4f9'
down_revision = 'baeecd787e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_channel_locations', sa.Column('location_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_channel_locations', 'location_id')
    # ### end Alembic commands ###
