"""empty message

Revision ID: b1eda94cffd7
Revises: 50bc5c4ba29d
Create Date: 2019-12-11 20:25:04.597354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1eda94cffd7'
down_revision = '50bc5c4ba29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manifests', sa.Column('total_picked', sa.Integer(), nullable=True))
    op.add_column('manifests', sa.Column('total_scheduled', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manifests', 'total_scheduled')
    op.drop_column('manifests', 'total_picked')
    # ### end Alembic commands ###
