"""empty message

Revision ID: b27f24715f49
Revises: 090c55c57b06
Create Date: 2021-06-01 15:36:39.718906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27f24715f49'
down_revision = '090c55c57b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pin_courier_id_unique', 'pincode_serviceability', ['pincode', 'courier_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pin_courier_id_unique', 'pincode_serviceability', type_='unique')
    # ### end Alembic commands ###
