"""empty message

Revision ID: b788eccc223b
Revises: 5051c12546c0
Create Date: 2021-02-10 21:34:04.369430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b788eccc223b'
down_revision = '5051c12546c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_ro', sa.Column('status', sa.String(), nullable=False, server_default='awaiting'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse_ro', 'status')
    # ### end Alembic commands ###
