"""empty message

Revision ID: b7add52829ca
Revises: 13590d38793e
Create Date: 2019-11-11 22:17:22.537066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7add52829ca'
down_revision = '13590d38793e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client_prefix', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'client_prefix')
    # ### end Alembic commands ###
