"""empty message

Revision ID: baeecd787e41
Revises: 3ded99f21bc6
Create Date: 2020-03-13 15:53:35.089197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baeecd787e41'
down_revision = '3ded99f21bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_channel_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pickup_data_id', sa.Integer(), nullable=True),
    sa.Column('client_channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_channel_id'], ['client_channel.id'], ),
    sa.ForeignKeyConstraint(['pickup_data_id'], ['client_pickups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_channel_locations')
    # ### end Alembic commands ###
