"""empty message

Revision ID: bf59d333bd3a
Revises: ad006fadd05f
Create Date: 2020-06-02 23:34:40.651157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf59d333bd3a'
down_revision = 'ad006fadd05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_prefix', sa.String(), nullable=True),
    sa.Column('warehouse_prefix', sa.String(), nullable=False),
    sa.Column('dimensions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subcategory_id'], ['products_subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_weights')
    # ### end Alembic commands ###
