"""empty message

Revision ID: c7fd3d33300f
Revises: 6b75521fdff0
Create Date: 2020-09-19 16:30:47.218307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7fd3d33300f'
down_revision = '6b75521fdff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_channels', sa.Column('integrated', sa.BOOLEAN(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_channels', 'integrated')
    # ### end Alembic commands ###
