"""empty message

Revision ID: ca0da9d05a00
Revises: 76c3b6017336
Create Date: 2020-03-16 18:25:45.145738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0da9d05a00'
down_revision = '76c3b6017336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_mapping', sa.Column('api_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_mapping', 'api_token')
    # ### end Alembic commands ###
