"""empty message

Revision ID: cb1fa3e6e35c
Revises: 16b051bfbfb5
Create Date: 2021-02-04 12:32:45.513498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1fa3e6e35c'
down_revision = '16b051bfbfb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_combos_combo_prod_id_fkey', 'products_combos', type_='foreignkey')
    op.drop_constraint('products_combos_combo_id_fkey', 'products_combos', type_='foreignkey')
    op.create_foreign_key(None, 'products_combos', 'master_products', ['combo_id'], ['id'])
    op.create_foreign_key(None, 'products_combos', 'master_products', ['combo_prod_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products_combos', type_='foreignkey')
    op.drop_constraint(None, 'products_combos', type_='foreignkey')
    op.create_foreign_key('products_combos_combo_id_fkey', 'products_combos', 'products', ['combo_id'], ['id'])
    op.create_foreign_key('products_combos_combo_prod_id_fkey', 'products_combos', 'products', ['combo_prod_id'], ['id'])
    # ### end Alembic commands ###
