"""client customizations

Revision ID: cdce758a8a31
Revises: 17dd01a6d45c
Create Date: 2021-07-21 10:27:51.271117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cdce758a8a31'
down_revision = '17dd01a6d45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_customization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_prefix', sa.String(), nullable=False),
    sa.Column('subdomain', sa.String(), nullable=True),
    sa.Column('client_logo_url', sa.String(), nullable=True),
    sa.Column('theme_color', sa.String(), nullable=True),
    sa.Column('background_image_url', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_url', sa.String(), nullable=True),
    sa.Column('nav_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('support_url', sa.String(), nullable=True),
    sa.Column('privacy_url', sa.String(), nullable=True),
    sa.Column('nps_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('banners', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_customization')
    # ### end Alembic commands ###
