"""empty message

Revision ID: cf13e1102841
Revises: 5b4448d3ee80
Create Date: 2019-11-10 14:06:44.938715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf13e1102841'
down_revision = '5b4448d3ee80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('inactive_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'inactive_reason')
    # ### end Alembic commands ###
