"""empty message

Revision ID: cfa5b317e4be
Revises: 01ce81f8225d
Create Date: 2020-12-29 17:21:03.490834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa5b317e4be'
down_revision = '01ce81f8225d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cod_remittance', sa.Column('del_from', sa.DateTime(), nullable=True))
    op.add_column('cod_remittance', sa.Column('del_to', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cod_remittance', 'del_to')
    op.drop_column('cod_remittance', 'del_from')
    # ### end Alembic commands ###
