"""empty message

Revision ID: d35e84603b5c
Revises: f3e8dfe1e5fc
Create Date: 2020-01-12 22:11:36.637249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35e84603b5c'
down_revision = 'f3e8dfe1e5fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_to_clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_prefix', sa.String(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('zone_a', sa.FLOAT(), nullable=True),
    sa.Column('zone_b', sa.FLOAT(), nullable=True),
    sa.Column('zone_c1', sa.FLOAT(), nullable=True),
    sa.Column('zone_c2', sa.FLOAT(), nullable=True),
    sa.Column('zone_d1', sa.FLOAT(), nullable=True),
    sa.Column('zone_d2', sa.FLOAT(), nullable=True),
    sa.Column('zone_e', sa.FLOAT(), nullable=True),
    sa.Column('zone_a_add', sa.FLOAT(), nullable=True),
    sa.Column('zone_b_add', sa.FLOAT(), nullable=True),
    sa.Column('zone_c1_add', sa.FLOAT(), nullable=True),
    sa.Column('zone_c2_add', sa.FLOAT(), nullable=True),
    sa.Column('zone_d1_add', sa.FLOAT(), nullable=True),
    sa.Column('zone_d2_add', sa.FLOAT(), nullable=True),
    sa.Column('zone_e_add', sa.FLOAT(), nullable=True),
    sa.Column('cod_min', sa.FLOAT(), nullable=True),
    sa.Column('cod_ratio', sa.FLOAT(), nullable=True),
    sa.Column('rto_ratio', sa.FLOAT(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['master_couriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cost_to_clients')
    # ### end Alembic commands ###
