"""empty message

Revision ID: d3f99f513f27
Revises: 61eaaf219f64
Create Date: 2020-03-11 18:04:02.766315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f99f513f27'
down_revision = '61eaaf219f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier_charges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forward_charge', sa.FLOAT(), nullable=True),
    sa.Column('rto_charge', sa.FLOAT(), nullable=True),
    sa.Column('cod_charge', sa.FLOAT(), nullable=True),
    sa.Column('total_charge', sa.FLOAT(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('weight_charged', sa.FLOAT(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('deduction_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courier_costs', sa.Column('first_step', sa.FLOAT(), nullable=True))
    op.add_column('courier_costs', sa.Column('next_step', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courier_costs', 'next_step')
    op.drop_column('courier_costs', 'first_step')
    op.drop_table('courier_charges')
    # ### end Alembic commands ###
