"""empty message

Revision ID: d4543fc00c81
Revises: 852c636aad18
Create Date: 2021-05-28 13:39:03.744587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4543fc00c81'
down_revision = '852c636aad18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_shortner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('hashid', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pincode_serviceability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pincode', sa.String(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('serviceable', sa.BOOLEAN(), nullable=True),
    sa.Column('cod_available', sa.BOOLEAN(), nullable=True),
    sa.Column('reverse_pickup', sa.BOOLEAN(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['master_couriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pincode_serviceability')
    op.drop_table('url_shortner')
    # ### end Alembic commands ###
