"""empty message

Revision ID: e4ca349f84f2
Revises: aadbbde56dae
Create Date: 2020-09-13 18:40:08.621974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ca349f84f2'
down_revision = 'aadbbde56dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_mapping', sa.Column('cod_man_ver', sa.BOOLEAN(), nullable=True))
    op.add_column('client_mapping', sa.Column('loc_assign_inventory', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_mapping', 'loc_assign_inventory')
    op.drop_column('client_mapping', 'cod_man_ver')
    # ### end Alembic commands ###
