"""empty message

Revision ID: e5b1b95bf76d
Revises: 2f339f005fe0
Create Date: 2021-01-13 21:22:31.527532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b1b95bf76d'
down_revision = '2f339f005fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_invoice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('pickup_data_id', sa.Integer(), nullable=True),
    sa.Column('invoice_no_text', sa.String(), nullable=False),
    sa.Column('invoice_no', sa.Integer(), nullable=False),
    sa.Column('cancelled', sa.BOOLEAN(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['pickup_data_id'], ['client_pickups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_invoice_order_id'), 'orders_invoice', ['order_id'], unique=True)
    op.add_column('client_pickups', sa.Column('invoice_last', sa.Integer(), nullable=True))
    op.add_column('client_pickups', sa.Column('invoice_prefix', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_pickups', 'invoice_prefix')
    op.drop_column('client_pickups', 'invoice_last')
    op.drop_index(op.f('ix_orders_invoice_order_id'), table_name='orders_invoice')
    op.drop_table('orders_invoice')
    # ### end Alembic commands ###
