"""empty message

Revision ID: e6f90b577ace
Revises: bf59d333bd3a
Create Date: 2020-06-02 23:47:28.228089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6f90b577ace'
down_revision = 'bf59d333bd3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword_weights', sa.Column('keywords', postgresql.ARRAY(sa.String(length=20)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword_weights', 'keywords')
    # ### end Alembic commands ###
