"""empty message

Revision ID: ea688f0bbb9d
Revises: 38b4f1647278
Create Date: 2019-12-05 15:24:57.665172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea688f0bbb9d'
down_revision = '38b4f1647278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_id_channel_unique', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('channel_fulfillment_id', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('edd', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'edd')
    op.drop_column('shipments', 'channel_fulfillment_id')
    op.drop_column('orders', 'order_id_channel_unique')
    # ### end Alembic commands ###
