"""empty message

Revision ID: edc89abefbcb
Revises: 18fa9454c05c
Create Date: 2019-11-11 20:50:15.577703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'edc89abefbcb'
down_revision = '18fa9454c05c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(), nullable=False))
    op.add_column('shipments', sa.Column('dimensions', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('shipments', sa.Column('volumetric_weight', sa.FLOAT(), nullable=True))
    op.add_column('shipments', sa.Column('weight', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'weight')
    op.drop_column('shipments', 'volumetric_weight')
    op.drop_column('shipments', 'dimensions')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
