"""empty message

Revision ID: ef76f9499ceb
Revises: f0da0281094a
Create Date: 2020-05-29 20:44:51.001284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef76f9499ceb'
down_revision = 'f0da0281094a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cod_remittance', sa.Column('client_prefix', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cod_remittance', 'client_prefix')
    # ### end Alembic commands ###
