"""empty message

Revision ID: efdcf52c1002
Revises: 68095d1f8c05
Create Date: 2020-12-30 22:21:55.240386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdcf52c1002'
down_revision = '68095d1f8c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weight_discrepency', sa.Column('remarks', sa.String(), nullable=True))
    op.drop_constraint('weight_discrepency_order_id_fkey', 'weight_discrepency', type_='foreignkey')
    op.drop_column('weight_discrepency', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weight_discrepency', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('weight_discrepency_order_id_fkey', 'weight_discrepency', 'orders', ['order_id'], ['id'])
    op.drop_column('weight_discrepency', 'remarks')
    # ### end Alembic commands ###
