"""empty message

Revision ID: efe4dcf0e77b
Revises: 2d5ab83d4d5a
Create Date: 2020-08-09 22:08:15.833075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe4dcf0e77b'
down_revision = '2d5ab83d4d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_channel', sa.Column('canceled_status', sa.String(), nullable=True))
    op.add_column('client_channel', sa.Column('delivered_status', sa.String(), nullable=True))
    op.add_column('client_channel', sa.Column('invoiced_status', sa.String(), nullable=True))
    op.add_column('client_channel', sa.Column('mark_canceled', sa.BOOLEAN(), nullable=True))
    op.add_column('client_channel', sa.Column('mark_delivered', sa.BOOLEAN(), nullable=True))
    op.add_column('client_channel', sa.Column('mark_invoiced', sa.BOOLEAN(), nullable=True))
    op.add_column('client_channel', sa.Column('mark_returned', sa.BOOLEAN(), nullable=True))
    op.add_column('client_channel', sa.Column('mark_shipped', sa.BOOLEAN(), nullable=True))
    op.add_column('client_channel', sa.Column('returned_status', sa.String(), nullable=True))
    op.add_column('client_channel', sa.Column('shipped_status', sa.String(), nullable=True))
    op.add_column('client_channel', sa.Column('unique_parameter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_channel', 'unique_parameter')
    op.drop_column('client_channel', 'shipped_status')
    op.drop_column('client_channel', 'returned_status')
    op.drop_column('client_channel', 'mark_shipped')
    op.drop_column('client_channel', 'mark_returned')
    op.drop_column('client_channel', 'mark_invoiced')
    op.drop_column('client_channel', 'mark_delivered')
    op.drop_column('client_channel', 'mark_canceled')
    op.drop_column('client_channel', 'invoiced_status')
    op.drop_column('client_channel', 'delivered_status')
    op.drop_column('client_channel', 'canceled_status')
    # ### end Alembic commands ###
