"""empty message

Revision ID: f0da0281094a
Revises: 59412dd2010e
Create Date: 2020-05-29 20:28:45.433016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0da0281094a'
down_revision = '59412dd2010e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cod_remittance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('remittance_id', sa.String(), nullable=False),
    sa.Column('remittance_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cod_remittance')
    # ### end Alembic commands ###
