"""empty message

Revision ID: f3e8dfe1e5fc
Revises: b9c33bba805d
Create Date: 2020-01-12 21:50:53.705527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e8dfe1e5fc'
down_revision = 'b9c33bba805d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('zone_a', sa.FLOAT(), nullable=True),
    sa.Column('zone_b', sa.FLOAT(), nullable=True),
    sa.Column('zone_c1', sa.FLOAT(), nullable=True),
    sa.Column('zone_c2', sa.FLOAT(), nullable=True),
    sa.Column('zone_d1', sa.FLOAT(), nullable=True),
    sa.Column('zone_d2', sa.FLOAT(), nullable=True),
    sa.Column('zone_e', sa.FLOAT(), nullable=True),
    sa.Column('zone_a_add', sa.FLOAT(), nullable=True),
    sa.Column('zone_b_add', sa.FLOAT(), nullable=True),
    sa.Column('zone_c1_add', sa.FLOAT(), nullable=True),
    sa.Column('zone_c2_add', sa.FLOAT(), nullable=True),
    sa.Column('zone_d1_add', sa.FLOAT(), nullable=True),
    sa.Column('zone_d2_add', sa.FLOAT(), nullable=True),
    sa.Column('zone_e_add', sa.FLOAT(), nullable=True),
    sa.Column('cod_min', sa.FLOAT(), nullable=True),
    sa.Column('cod_ratio', sa.FLOAT(), nullable=True),
    sa.Column('rto_ratio', sa.FLOAT(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['master_couriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courier_costs')
    # ### end Alembic commands ###
