"""empty message

Revision ID: f4a0870df09b
Revises: 1f82f485d255
Create Date: 2020-07-05 12:42:11.632926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a0870df09b'
down_revision = '1f82f485d255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sku_unique', 'products', ['sku', 'client_prefix', 'channel_id'])
    op.drop_constraint('products_sku_key', 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('products_sku_key', 'products', ['sku'])
    op.drop_constraint('sku_unique', 'products', type_='unique')
    # ### end Alembic commands ###
