"""empty message

Revision ID: f4fd7405c310
Revises: 0836f81bde11
Create Date: 2021-05-10 20:49:25.170629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fd7405c310'
down_revision = '0836f81bde11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_order_id', sa.String(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('synced', sa.BOOLEAN(), nullable=True),
    sa.Column('client_prefix', sa.String(), nullable=True),
    sa.Column('client_channel_id', sa.Integer(), nullable=True),
    sa.Column('master_channel_id', sa.Integer(), nullable=True),
    sa.Column('order_id_channel_unique', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_channel_id'], ['client_channel.id'], ),
    sa.ForeignKeyConstraint(['master_channel_id'], ['master_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failed_orders')
    # ### end Alembic commands ###
