"""empty message

Revision ID: f89b99319494
Revises: 3f7727c46790
Create Date: 2020-11-03 15:45:27.243843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89b99319494'
down_revision = '3f7727c46790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_extra_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user_created_at', sa.String(), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=True),
    sa.Column('verified_email', sa.BOOLEAN(), nullable=True),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('payment_gateway', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_extra_details_order_id'), 'orders_extra_details', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_extra_details_order_id'), table_name='orders_extra_details')
    op.drop_table('orders_extra_details')
    # ### end Alembic commands ###
