"""empty message

Revision ID: fa2e7bb687c1
Revises: a6c4dbd85bf9
Create Date: 2020-11-06 17:26:07.749970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2e7bb687c1'
down_revision = 'a6c4dbd85bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_mapping', sa.Column('lock_cod', sa.BOOLEAN(), nullable=True))
    op.add_column('cod_remittance', sa.Column('remitted_amount', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cod_remittance', 'remitted_amount')
    op.drop_column('client_mapping', 'lock_cod')
    # ### end Alembic commands ###
